language: go
go:
        - 1.x
os:
        - linux
before_install:
        - go get github.com/golang/lint/golint
        - go get honnef.co/go/tools/cmd/staticcheck
        - go get -d ./...
script:
        - go build ./...
        - go vet ./...
        - staticcheck ./...
        - go test -race -v ./...
